- name: ETC setup steps
  hosts: etc
  become: True
  tasks:
    - name: Include app variables
      include_vars: vars.yml
      
    - name: Rename Machine
      ansible.builtin.lineinfile:
        path: /etc/hostname
        regexp: '^{{ server_default_name }}'
        line: '{{ server_chosen_name }}'

    - name: Reboot machine to populate name change
      ansible.builtin.reboot: